language: cpp
os: osx

before_install:
  - brew update && brew install openssl

env:
  - CMAKE_OPTS="-DBUILD_32=OFF -DSEPARATION=ON -DNBODY=OFF -DSEPARATION_OPENCL=ON"
  - CMAKE_OPTS="-DBUILD_32=OFF -DSEPARATION=OFF -DNBODY=ON -DNBODY_OPENCL=ON"

script:
  - cmake ${CMAKE_OPTS}
  - make
